<?php

namespace Bibliotheek\BoekBundle\Repository;

/**
 * BoekRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoekRepository extends \Doctrine\ORM\EntityRepository
{
}
